### ISSUE TITLE
"province" field in ISO3166CitiesMunicipality interface to be nullable

### ISSUE THREAD

**Issue by junedomingo** [hyubs/ph-locations#11]
https://github.com/hyubs/ph-locations/blob/b5feb0e251561d88ea1671552c720a724097191e/%40types/index.d.ts#L5

Some city doesn't have province value like Quezon city, Pateros, San Juan City, ...

**Comment by hubertursua** [comment]
Thanks! To be corrected in an upcoming release next week.
—
Keeping this issue open until the commit is pushed.

**Comment by hubertursua** [comment]
Closing. Already resolved in develop branch. Will be released in v1.2.0.
